### ISSUE TITLE
Every collection record gets pulled and enumerated

### ISSUE THREAD

**Issue by brian-pickens** [i3arnon/MongoAsyncEnumerableAdapter#1]
This is just a heads up to the dev and potential library users. When using this library to convert the IMongoCollection to an AsyncEnumerable, it will enumerate every collection record in order to execute whatever linq method you use.

**Comment by i3arnon** [comment]
Do you mean to say that the operators execute in the client side and not in the mongo server?
If so.. then of course. It's async **enumerable**, not async **queryable**.

For the operators you want to run server side you should use the mongo client's API and only then covert to async enumerable. There's an example in the [readme file](https://github.com/i3arnon/MongoAsyncEnumerableAdapter/blob/main/README.md) and much more [on my blog](https://blog.i3arnon.com/2015/12/16/async-linq-to-objects-over-mongodb)

**Comment by brian-pickens** [comment]
Yes, I fully admit I missunderstood this about IAsyncEnumerable and Enumerable vs Queryable until recently.
